import os
import PyPDF2
import io
from google import genai
from google.genai import types
from ..core.configs import settings
from ..prompts.prompts import ACBP_DOCUMENT_SUMMARY_PROMPT
from ..core.logger import logger

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = settings.GOOGLE_APPLICATION_CREDENTIALS

class PDFProcessingService:
    """Service for processing PDF files and generating summaries using Google LLM"""
    
    def __init__(self):
        """Initialize the PDF processing service with Google AI configuration"""
        try:
            self.client = genai.Client(
                project=settings.GOOGLE_PROJECT_ID,
                location="us-central1",
                vertexai=True
            )
            logger.info("Google AI service initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize Google AI service: {str(e)}")
            raise
    
    def extract_text_from_pdf(self, pdf_content: bytes) -> str:
        """
        Extract text content from PDF bytes
        
        Args:
            pdf_content: PDF file content as bytes
            
        Returns:
            str: Extracted text content from PDF
        """
        try:
            logger.info("Starting PDF text extraction")
            
            # Create a BytesIO object from the PDF content
            pdf_stream = io.BytesIO(pdf_content)
            
            # Create PDF reader object
            pdf_reader = PyPDF2.PdfReader(pdf_stream)
            
            # Extract text from all pages
            extracted_text = ""
            total_pages = len(pdf_reader.pages)
            
            logger.info(f"Processing PDF with {total_pages} pages")
            
            for page_num, page in enumerate(pdf_reader.pages):
                try:
                    page_text = page.extract_text()
                    extracted_text += f"\n--- Page {page_num + 1} ---\n{page_text}\n"
                    logger.debug(f"Extracted text from page {page_num + 1}")
                except Exception as e:
                    logger.warning(f"Failed to extract text from page {page_num + 1}: {str(e)}")
                    continue
            
            if not extracted_text.strip():
                logger.warning("No text content extracted from PDF")
                return ""
            
            logger.info(f"Successfully extracted {len(extracted_text)} characters from PDF")
            return extracted_text.strip()
            
        except Exception as e:
            logger.error(f"Error extracting text from PDF: {str(e)}")
            raise Exception(f"PDF text extraction failed: {str(e)}")
    
    async def generate_acbp_plan_summary(self, text_content: bytes) -> str:
        """
        Generate summary for ACBP Plan using Google LLM
        
        Args:
            text_content: Extracted text content from ACBP Plan PDF
            
        Returns:
            str: AI-generated summary of the ACBP Plan
        """
        try:
            logger.info("Generating ACBP Plan summary using Google LLM")
            contents = [ 
                types.Content(
                    role="user", 
                    parts=[
                        types.Part.from_bytes(
                            data=text_content,
                            mime_type='application/pdf',
                        ),
                        types.Part.from_text(text=ACBP_DOCUMENT_SUMMARY_PROMPT)
                    ]
                )
            ]

            generate_content_config = types.GenerateContentConfig(
                temperature = 1,
                top_p = 0.95,
                seed = 0,
                max_output_tokens = 65535,
                safety_settings = [types.SafetySetting(
                category="HARM_CATEGORY_HATE_SPEECH",
                threshold="OFF"
                ),types.SafetySetting(
                category="HARM_CATEGORY_DANGEROUS_CONTENT",
                threshold="OFF"
                ),types.SafetySetting(
                category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                threshold="OFF"
                ),types.SafetySetting(
                category="HARM_CATEGORY_HARASSMENT",
                threshold="OFF"
                )],
                thinking_config=types.ThinkingConfig(
                thinking_budget=-1,
                ),
            )
            
            response = await self.client.aio.models.generate_content(
                model="gemini-2.5-pro",
                contents=contents,
                config=generate_content_config
            )
            print("ACBP PLAN SUMMARY::", response.usage_metadata)
            summary = response.text
            
            if not summary:
                logger.warning("Empty summary generated by Google LLM")
                return "Summary generation failed - no content returned"
            
            logger.info(f"Successfully generated ACBP Plan summary ({len(summary)} characters)")
            return summary
            
        except Exception as e:
            logger.error(f"Error generating ACBP Plan summary: {str(e)}")
            return f"Summary generation failed: {str(e)}"
    
    async def generate_work_allocation_summary(self, text_content: bytes) -> str:
        """
        Generate summary for Work Allocation Order using Google LLM
        
        Args:
            text_content: Extracted text content from Work Allocation Order PDF
            
        Returns:
            str: AI-generated summary of the Work Allocation Order
        """
        try:
            logger.info("Generating Work Allocation Order summary using Google LLM")
            
            prompt = f"""
            You are an expert analyst specializing in Work Allocation Order documents for government and organizational projects. Please analyze the provided Work Allocation Order PDF document and create a comprehensive, structured summary.

            Focus on extracting and summarizing:
            1. Work order details and reference numbers
            2. Allocated tasks and responsibilities
            3. Personnel assignments and roles
            4. Timeline and deadlines
            5. Resource allocation and budget
            6. Deliverables and expected outcomes
            7. Quality standards and requirements
            8. Reporting and monitoring mechanisms
            9. Approval authorities and stakeholders

            **Output Format:**
            Provide a well-structured summary that captures all essential elements of the Work Allocation Order. Use clear headings, bullet points where appropriate, and ensure the summary provides actionable insights for project execution.

            Please analyze the PDF document and provide your comprehensive summary:
            """

            # prompt = DOC_SUMMARY_PROMPT
            
            contents = [   
                types.Content(
                    role="user", 
                    parts=[
                        types.Part.from_bytes(
                            data=text_content,
                            mime_type='application/pdf',
                        ),
                        types.Part.from_text(text=prompt)
                    ]
                )
            ]

            generate_content_config = types.GenerateContentConfig(
                temperature = 1,
                top_p = 0.95,
                seed = 0,
                max_output_tokens = 65535,
                safety_settings = [types.SafetySetting(
                category="HARM_CATEGORY_HATE_SPEECH",
                threshold="OFF"
                ),types.SafetySetting(
                category="HARM_CATEGORY_DANGEROUS_CONTENT",
                threshold="OFF"
                ),types.SafetySetting(
                category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                threshold="OFF"
                ),types.SafetySetting(
                category="HARM_CATEGORY_HARASSMENT",
                threshold="OFF"
                )],
                thinking_config=types.ThinkingConfig(
                thinking_budget=-1,
                ),
            )
            
            response = await self.client.aio.models.generate_content(
                model="gemini-2.5-pro",
                contents=contents,
                config=generate_content_config
            )
            print("WORK ALLOCATION SUMMARY::", response.usage_metadata)
            summary = response.text
            
            if not summary:
                logger.warning("Empty summary generated by Google LLM")
                return "Summary generation failed - no content returned"
            
            logger.info(f"Successfully generated Work Allocation Order summary ({len(summary)} characters)")
            return summary
            
        except Exception as e:
            logger.error(f"Error generating Work Allocation Order summary: {str(e)}")
            return f"Summary generation failed: {str(e)}"
    
    async def process_pdf_and_generate_summary(self, pdf_content: bytes, document_type: str) -> str:
        """
        Process PDF and generate appropriate summary based on document type
        
        Args:
            pdf_content: PDF file content as bytes
            document_type: Type of document ('acbp_plan' or 'work_allocation')
            
        Returns:
            str: Generated summary
        """
        try:
            logger.info(f"Processing PDF for document type: {document_type}")
                    
            # Generate summary based on document type
            if document_type == "acbp_plan":
                summary = await self.generate_acbp_plan_summary(pdf_content)
            elif document_type == "work_allocation":
                summary = await self.generate_work_allocation_summary(pdf_content)
            else:
                logger.error(f"Unknown document type: {document_type}")
                return f"Unknown document type: {document_type}"
            
            logger.info(f"Successfully processed PDF and generated summary for {document_type}")
            return summary
            
        except Exception as e:
            logger.error(f"Error processing PDF for {document_type}: {str(e)}")
            return f"PDF processing failed: {str(e)}"

# Create a singleton instance
pdf_service = PDFProcessingService()